palette:
  top: '#fe2aac'
  bottom: '#fd8bdf'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-7c86532b/logo.svg'
stylesheets:
  - 'public://color/bartik-7c86532b/colors.css'
files:
  - 'public://color/bartik-7c86532b/logo.svg'
  - 'public://color/bartik-7c86532b/colors.css'
